ability to specify binding host, vague ipv6 support
Theldus/wsServer pull request #56
Opened 2022-05-07 14:46 UTC by refutationalist

I wanted to be able to bind to localhost where I use wsServer for reverse proxying purposes, which means it would also be helpful if I could see which client port it was connecting from.  One of the localhost interfaces I bind to is ::1, so some changes were necessary to fit ipv6 into it.

I guess this modernizes things a bit?

The main API change is that ws_socket requires a host char*, though setting it to NULL returns it to the previous behavior.   Also, the port is also a char* now.

2022-05-12 17:37 UTC, Theldus requested changes
Hi @refutationalist,
I think the possibility to choose the binding address is quite interesting... it had never occurred to me to add something like this before.

However, there are a few things I would like to discuss first:
- **a)** As per Travis CI builds, [your PR doesn't build for Windows](https://app.travis-ci.com/github/Theldus/wsServer/jobs/570040201). 

- **b)** I'm not sure I like the idea of saving the port as a string. I understand that the parameter of `getaddrinfo()` is a string... but it bothers me a bit to have it saved as a string.

- **c)** One more parameter in `ws_socket()`. I would like to avoid adding more parameters to this function by introducing a special structure to define these types of parameters, something like:
```c
struct ws_server
{
  /* Server bind and port. */
  const char *host;
  uint16_t port;

  /* Timeout. */
  int timeout_ms;

  /* Events. */
  struct ws_events evs;

  /* Internal stuff. */
  ...
};

struct ws_server ws = {
  .host = "localhost",
  .port = 8080,
  ...
};

/* and later. */
ws_socket(&ws);

/* or even. */
ws_socket((struct ws_server)
  {
    .host = "localhost",
    .port = 8080,
    .timeout_ms = 1000,
    .evs.onopen = &on_open,
    .evs.onclose = &on_close,
    .evs.onmessage = &on_message
  }
);
```
(but don't worry about it, I'm just sharing my ideas for the future)

- **d)** Your email address... not exactly an issue but... if I accept your PR as is, you won't be listed as a 'contributor' by GitHub, as it doesn't recognize the email used in the commits (which needs to be the same as the used in your account).

  If you want to hide it for some reason, no problem, but if you want, rebase your commits by changing the author to '`sam[at]vis[dot]nu`' (I took a look at another repo of yours 😉).

---

Anyway, don't mind with all I've said, the only points I hope you'll work on are **a)** and optionally **d)**.

2022-05-13 03:59 UTC, refutationalist commented
Hello!

- **a)** I suspected that might be the case, but would need help on that as I've done exactly zero windows development.   Probably should have mentioned that in the original PR, but it was pretty late in the day.   Willing to do what I can.
- **b)** That makes sense as service names don't help us very much, I just wasn't seeing any type conversions and decided to stick with that.
- **c)** That strikes me as good.   I appreciate the desire to keep the parameter list under control, as long as I can still control which interfaces I'm binding to.
- **d)** I'm not primarily a developer, so I'm new at this PR deal, I'll make whatever changes would be easiest, which seems to be changing the email address on my end.

2022-05-13 06:37 UTC, Theldus commented
> Hello!
> 
> * **a)** I suspected that might be the case, but would need help on that as I've done exactly zero windows development.   Probably should have mentioned that in the original PR, but it was pretty late in the day.   Willing to do what I can.

Looking at the [Windows docs](https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/), the functions `getaddrinfo()` and `getnameinfo()` (from <netdb.h>) are already included in the Windows '`<ws2tcpip.h>`' header, which is already included in the wsServer.

The only header you need to add is `<netdb.h>` for builds in Unix-like environments, or rather for non-Windows environments. Something like [this](https://github.com/Theldus/wsServer/commit/e6831ad7b74b44c9a3780bb2ea3ab18f723f7bd0) should work.

> * **d)** I'm not primarily a developer, so I'm new at this PR deal.  I'll make whatever changes would be easiest, which seems to be changing the email address on my end.

No worries, I'm open to receiving contributions from anyone, and helping within my possibilities as well =).

2022-06-22 07:18 UTC, refutationalist commented
Just a quick note:I haven't forgotten about this PR, summer is a crunch time for me and I haven't been able to spend a lot of time in front of the editor.   I'll be back at it as soon as I can.

2022-06-23 06:38 UTC, Theldus commented
> Just a quick note:I haven't forgotten about this PR, summer is a crunch time for me and I haven't been able to spend a lot of time in front of the editor. I'll be back at it as soon as I can.

Hey @refutationalist,

No worries,
If you do not mind, I can work on what we discussed earlier to get this PR merged, basically: fix the build for Windows, and the email address used. In fact I was hoping you'd give me an 'ok' to work on it, since it's quite simple.

The remaining I can address later, as they require major changes and I prefer to do them myself.

2022-06-23 07:00 UTC, refutationalist commented
On 6/22/22 23:38, Davidson Francis wrote:
>
> If you do not mind, I can work on what we discussed earlier to get 
> this PR merged, basically: fix the build for Windows, and the email 
> address used. In fact I was hoping you'd give me an 'ok' to work on 
> it, since it's quite simple.
>
> The remaining I can address later, as they require major changes and I 
> prefer to do them myself.
>

Absolutely no problem.  Thank you!

2023-08-02 08:08 UTC, arhiv6 commented
I will wait this features too. I use this library and it work perfect (thanks for your work, @Theldus\). But, I need to bind _localhost_ too and this PR look promising. Has the work been stopped?

2023-11-28 06:08 UTC, Theldus commented
Hi @refutationalist and @arhiv6,
The new PR #82 finally reviews all the points I covered here and is finally merged. If you encounter any issues with the implementation, please let me know.

That said, I will close this PR and again, thank you very much for the contribution.

2023-11-28 06:08 UTC, closed without merging